site_name: Wavely Docs
site_url: https://platform.wavely.io
site_description: The Wavely Platform
site_author: Wavely Team

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

pages:
  - Home: 'index.md'
  - General information:
      - About: 'general-information/wavely-api-docs.md'
      - Roles: 'general-information/roles.md'
      - Data types: 'general-information/data-types.md'
      - General errors: 'general-information/general-errors.md'
  - Web hooks:
      - About webhooks: 'webhooks/about-webhooks.md'
      - Call CDR: 'webhooks/call-cdr.md'
      - Data CDR: 'webhooks/data-cdr.md'
      - Message CDR: 'webhooks/msg-cdr.md'
      - SMS forwarding: 'webhooks/sms-forwarding.md'
      - SIM card state change: 'webhooks/sim-card-state-change.md'
  - API specification:
      - SMS: 'api/sms-api.md'
      - SIM cards: 'api/simcards-api.md'
      - Operator profiles: 'api/operator-profiles.md'
      - SIM card diagnostics: 'api/sim-card-diagnostics.md'
      - SIM card usage: 'api/sim-card-usage.md'
      - SIM card groups: 'api/simcard-groups.md'
      - SIM card tags: 'api/simcard-tags.md'
      - Call forwarding: 'api/call-forward.md'
      - Data Usage API: 'api/data-usage-api.md'
      - Invoice API: 'api/invoice-api.md'
      # This should be refactored after external APIs will be known
      # - Invite Owner API: 'api/invite-owner.md'
      - MLT - Multi Level Tenancy: 'api/mlt.md'
      - Context API: 'api/context.md'
      - Customer API: 'api/sub-account.md'
      - Phone number API: 'api/phone-numbers-api.md'
      - SIP peers API: 'api/sippeers-api.md'
