site_name: Wavely Docs
site_url: https://docs.wavely.io
site_description: The Wavely Platform
site_author: Wavely Team

theme:
  name: material

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Home: 'index.md'
  - 'General information':
      - About: 'general-information/wavely-api-docs.md'
      - Roles: 'general-information/roles.md'
      - 'Data types': 'general-information/data-types.md'
      - 'General errors': 'general-information/general-errors.md'
  - 'Webhooks':
      - 'About webhooks': 'webhooks/about-webhooks.md'
      - 'Call CDR': 'webhooks/call-cdr.md'
      - 'Data CDR': 'webhooks/data-cdr.md'
      - 'Message CDR': 'webhooks/msg-cdr.md'
      - 'SMS Forwarding': 'webhooks/sms-forwarding.md'
      - 'SIM card state change': 'webhooks/sim-card-state-change.md'
  - 'API specification':
      - SMS: 'api/sms.md'
      - 'SIM cards': 'api/simcards.md'
      - 'Operator profiles': 'api/operator-profiles.md'
      - 'SIM card diagnostics': 'api/simcard-diagnostics.md'
      - 'SIM card usage': 'api/simcard-usage.md'
      - 'SIM card groups (collections)': 'api/simcard-groups.md'
      - 'SIM card tags': 'api/simcard-tag.md'
      - 'Call Forwarding': 'api/call-forwarding.md'
      - 'Company Data Usage': 'api/company-data-usage.md'
      - 'Geolocation': 'api/geolocation.md'
      # This should be refactored after external APIs will be known
      # - Invite Owner API: 'api/invite-owner.md'
      - 'MLT - Multi Level Tenancy': 'api/multi-level-tenancy.md'
      - 'Voice Service':
        - 'Contexts': 'api/voice-service-contexts.md'
        - 'Customers': 'api/voice-service-customers.md'
        - 'Phone numbers': 'api/voice-service-phone-numbers.md'
        - 'SIP peers': 'api/voice-service-sippeers.md'
